on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Unit-Test

jobs:
  ledis-unit-test:
    strategy:
      matrix:
        go-version: [1.23.x]
        os: [ubuntu-latest]
        arch: [amd64, arm64, armv5, armv6, armv7]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run unit tests
        run: |
          cd ledis
          go test -v ./...
